### ISSUE TITLE
Store portal names

### ISSUE THREAD

**Issue by hrw** [OllieTerrance/IITCTeamKeys#1]
I do not know how much work it would require but would be nice to have portal names stored with keys.

It is quite hard to remember which portal {eda237ebe7584c3096e045dd3eb2f1de.16} is.

**Comment by Terrance** [comment]
Apologies for the delay, I haven't worked on this in a while.  There is a built-in cache for portal names (such that known portals are synced to other team members), however this may have broke due to intel site changes.

Whilst I have some portals listed in the cache table, I am indeed also seeing some without a name.  It should start displaying once the portal is visible.

**Comment by Terrance** [comment]
Having just revisited this, I think caching should be working again now...

You build your own cache of portal names as you explore the map -- this is synced to the server and distributed to other members in your team.
